server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: service-01

app.task.id: "taskId"

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:1111/eureka/}
    register-with-eureka: true
    fetch-registry: true
