server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: service-01

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
    register-with-eureka: true
    fetch-registry: true
