version: "3.9"  # optional since v1.27.0
services:
  service-registry-1:
    build: eureka-server
    expose:
    - 1111
    ports:
    - 1111:1111
    environment:
      DISCOVERY_SERVER: http://service-registry-2:1111/eureka/
      eureka.instance.hostname: service-registry-1
  service-registry-2:
    build: eureka-server
    expose:
    - 1111
    ports:
    - 1112:1111
    environment:
      DISCOVERY_SERVER: http://service-registry-1:1111/eureka/
      eureka.instance.hostname: service-registry-2
  svc-service01:
    build: service01
    deploy:
      mode: replicated
      replicas: 2
    environment:
      app.task.id: "$${HOSTNAME}"
      SERVER_PORT: 8080
      DISCOVERY_SERVER: http://service-registry-2:1111/eureka/,http://service-registry-1:1111/eureka/
    expose:
    - 8080
  svc-service02:
    build: service02
    environment:
      SERVER_PORT: 8080
      DISCOVERY_SERVER: http://service-registry-2:1111/eureka/,http://service-registry-1:1111/eureka/
    expose:
    - 8080
    deploy:
      mode: replicated
      replicas: 2
  gateway:
    build: gateway
    environment:
      SERVER_PORT: 8080
      DISCOVERY_SERVER: http://service-registry-2:1111/eureka/,http://service-registry-1:1111/eureka/
    expose:
    - 8080
    ports: 
    - 8082:8080