server:
  port: 1111

spring:
  application:
    name: EurekaServer

management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
    register-with-eureka: false
    fetch-registry: false