server:
  port: 1111

spring:
  application:
    name: EurekaServer

management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:${server.port}/eureka/}
    register-with-eureka: false
    fetch-registry: false